name: Build and deploy Node.js app to Azure Web App - pubnetwork

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: npm install and build
        run: |
          npm ci
          npm run build
        env:
          REDIRECT_PART1: ${{ secrets.REDIRECT_PART1 }}
          REDIRECT_PART2: ${{ secrets.REDIRECT_PART2 }}

      - name: Add production configuration
        run: |
          echo '{ "scripts": { "start": "next start -p 8080" } }' >> package.json

      - name: Zip artifact for deployment
        run: zip release.zip ./* .next .env* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6A0D0EF97B3C4230AAD6F42BA6BA2F82 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DB36257D5E3445368359FECEF08580C3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_20C297F738144489B7A94B0A1546AD8D }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pubnetwork'
          slot-name: 'Production'
          package: .
          
      - name: Configure Azure App Service
        uses: azure/appservice-settings@v1
        with:
          app-name: 'pubnetwork'
          app-settings-json: |
            [
              {
                "name": "WEBSITES_PORT",
                "value": "8080"
              },
              {
                "name": "NODE_ENV",
                "value": "production"
              },
              {
                "name": "REDIRECT_PART1",
                "value": "${{ secrets.REDIRECT_PART1 }}"
              },
              {
                "name": "REDIRECT_PART2",
                "value": "${{ secrets.REDIRECT_PART2 }}"
              }
            ]
